config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :events, only: [:create, :show, :new, :update, :group] do
    resources :attendees, only: [:create, :new]
  end
  resources :events do
    member do
      get :group
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :email, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :attendees

  validates :title, presence: true
  validates :description, presence: true
  validates :date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :users
  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController

  def new
    @attendee = Attendee.new
  end

  def create
    @event = Event.find(params[:event_id]) #---> recup l'event id
    @attendee = Attendee.new(event_id: params[:event_id]) # ---> donne event_id a la nouvelle instance d'attendee
    @attendee.user = current_user #----> donne user_id a l'instance @attendee
    @attendee.update(attendee_params) # ---> me permets de recuperer l'email
    @attendee.save
    redirect_to event_path(Event.find(params[:event_id]), notice: 'Event was successfully created.')
  end

  private

  def attendee_params
    params.require(:attendee).permit(:email)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
    @attendee = Attendee.new
  end

  def group #(group of attendee)

    #Creer le group de participants avec tous les mails (attendee_list)
    @attendee_list = []
    @event = Event.find(params[:id])
    @event.attendees.each do |attendee|
      @attendee_list << attendee.email
    end
    @event.save

    # associer de manière aléatoire un utilisateur à un autre
    @pairs_shuffled = @attendee_list.shuffle
    @pairs_shuffled << @pairs_shuffled.first #reprendre le premier attendee
    @assignments = @pairs_shuffled.each_cons(2).to_a
  end


  private
  def event_params
    params.require(:event).permit(:title, :description, :date, :max_amount, :group)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @events = Event.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/group.html.slim
.container
  h1 Hello !
  h5 Here is the pair assignments between the attendees of the event
  - @assignments.each do |attendee|
    li
      strong
        = attendee.first
      | has to send a gift to
      strong
        = attendee.last
      | (
      small
        = attendee.first
        | will receive by email the name of #{attendee.last}
      | )
  br/
  .text-center
    h1 Happy Secret Santa ! 🎁💫

app/views/events/new.html.slim
.new
  .container
    .form
      h4
        strong Give us some information about your next Secret Santa ! 🎁
      = simple_form_for [ @event] do |f|
        = f.input :title, label: "EVENT'S TITLE"
        = f.input :description, label: "DESCRIPTION"
        = f.input :max_amount, label: "AMOUNT TO SPEND (€)"
        = f.input :date, label: "DATE"
        .text-center
          = f.submit "Create your Secret Santa", class: "btn btn-primary"

app/views/events/show.html.slim
.container
  .text-center
    h1
      = @event.title
      |  🎁
  .details
    p
      | Description :
      strong
        = @event.description
    p
      |  Each person has to spend:
      strong
        = @event.max_amount
      |€
    p
      |Date:
      strong
        = @event.date
  = simple_form_for [@event, @attendee] do |f|
    = f.input :email, label:"Give the e-mail of your participants"
    = f.button :submit, "+ New participant", class: "btn btn-primary"
  .list
    h5
      | The list of your participants(
      = @event.attendees.size + 1
      | ):
    |  1 -
    = @event.user.email
    |  (organizer)
    - @event.attendees.each_with_index do |attendee, index|
      li
        = index + 2
        |  -
        = attendee.email
  .text-center
    = link_to group_event_path do
      p.button-start
        |  Send emails to the participants
    p
      small
        | (By clicking, you will randomly assign persons to each other to give a present to one another.)

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content: "text/html; charset=UTF-8" http-equiv="Content-Type" /
    title SecretSantaTest
    = csrf_meta_tags
    = csp_meta_tag
    meta content: "width=device-width, initial-scale=1, shrink-to-fit=no", name: "viewport" /
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true
  body
    = render 'shared/navbar'
    = render 'shared/flashes'
    = yield

app/views/pages/home.html.slim
.home
  .container
    .text
      h1 Secret Santa App!
      p#explanation
        | What is Secret Santa?
        | It’s a free online Secret Santa gift exchange organizer / Kris Kringle generator! Organize a Secret Santa party with friends, family or even co-workers. After receiving the Secret Santa mail you can add your own wishlist, which will be delivered to your Secret Santa.
        | Each year around Christmas time people all over the world exchange gifts.
        | To keep things interesting though, you can randomly assign persons to each other to give a present to one another.
    .text-center
      = link_to "Start your Secret Santa !", new_event_path, class: "button-start"

app/views/shared/_flashes.html.slim
- if notice
  .alert.alert-info.alert-dismissible.fade.show.m-1 role: "alert" 
    = notice
    button.close aria-label="Close" data-dismiss="alert", type: "button" 
      span aria-hidden="true"  ×
- if alert
  .alert.alert-warning.alert-dismissible.fade.show.m-1 role: "alert" 
    = alert
    button.close aria-label="Close" data-dismiss="alert", type: "button" 
      span aria-hidden="true"  ×

app/views/shared/_navbar.html.slim
.navbar.navbar-expand-sm.navbar-light.navbar-lewagon
  = link_to root_path, class: "navbar-brand" do
    = image_tag "https://santa.gl/wp-content/uploads/logo_1_256.png"
  button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse", type: "button" 
    span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      - if user_signed_in?
        li.nav-item.active
          = link_to "Home", root_path, class: "nav-link"
        li.nav-item.dropdown
          = image_tag "https://kitt.lewagon.com/placeholder/users/EricKuoch", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false
          .dropdown-menu.dropdown-menu-right aria-labelledby="navbarDropdown" 
            = link_to "Action", "#", class: "dropdown-item"
            = link_to "Another action", "#", class: "dropdown-item"
            = link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item"
      - else
        li.nav-item
          = link_to "Login", new_user_session_path, class: "nav-link"